### ISSUE TITLE
convertDateTime bug em CadastroUsuario.xhtml

### ISSUE THREAD

**Issue by lucascco** [lucascco/Officium#1]
Ao converter o value do h:input para o atributo Date da classe usuario, o dia é convertido de forma errada, exemplo:
10/02/1991 é convertido no lado servidor para 09/02/1991

Trecho do código em CadastroUsuario.xhtml linha:51
`<h:inputText label="#{app['label.nascimento']}" class="form-control" id="ipt_nascimento_cad" value="#{cadastroUsuarioBean.usuario.nascimento}">
    <f:convertDateTime pattern="dd/MM/yyyy"/>
 </h:inputText>`

**Comment by lucashvalentim** [comment]
Qual o contexto desse e-mail ?

2015-10-09 1:26 GMT-03:00 Lucas Carvalho Corrêa notifications@github.com:

**Comment by lucascco** [comment]
Isto é uma Issue (Uma pendencia no projeto), pode ser um bug ou uma melhoria. Sempre q um colaborador abre uma issue todos do projeto recebem um e-mail. Qualquer um no projeto pode pegar e resolver a pendencia, assim q resolvida, ela é fechada.

**Comment by lucashvalentim** [comment]
Agora faz sentido :) !

Em 9 de outubro de 2015 14:23, Lucas Carvalho Corrêa <
notifications@github.com> escreveu:
